id: c02b5598d4e34eb0b8a6da4559692811
initial_creation_type: ocr
created_at: 24/09/2021
last_modified_at: 2021-12-20 10:25:20.581056
source_metadata:
  id: bdr:W29040
  title: བོད་ཀྱི་དམངས་སྲོལ་དང་འབྲེལ་བའི་སྐར་རྩིས
  volumes:
    b50a06e06b7f4ea1b227a7de3ba699bf:
      image_group_id: I1PD366
      title: ''
      base_file: v001.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
